server:
  port : 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: f8053e8cdd6efd9d0698
            clientSecret: b7c2d2500ac97226ee3fd7118ae03ee3423a5903
