server:
  port : 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: spalod

    
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 46d5da3810de3587035b
            clientSecret: 7c521fa36a579e48d95b0bb58ba68c78aef454bb

# application.properties
triplestore.sparqlEndpoint: http://example.com/sparql

