export const queryables = [
  {
    q: "title",
    required: true,
    d: "The name given to the resource",
    v: false,
    p: "http://purl.org/dc/terms/title",
    literal: true,
  },
  {
    q: "description",
    required: true,
    d: "Description of the resource",
    v: false,
    p: "http://purl.org/dc/terms/description",
    literal: true,
  },
  {
    q: "distribution",
    required: true,
    d: "The url of the distribution",
    v: false,
    p: "http://www.w3.org/ns/dcat#distribution",
    literal: false,
  },
  {
    q: "publisher",
    required: true,
    d: "Entity making the resource available",
    v: false,
    p: "http://purl.org/dc/terms/publisher",
    literal: false,
  },
  {
    q: "keywords",
    required: false,
    d: "Tags separated by ','",
    v: false,
    p: "http://www.w3.org/ns/dcat#keyword",
    literal: true,
  },
  {
    q: "theme",
    required: false,
    d: "Categories separated by ','",
    v: false,
    p: "http://www.w3.org/ns/dcat#theme",
    literal: false,
  },
  {
    q: "type",
    required: false,
    d: "The nature or genre of the resource",
    v: false,
    p: "http://purl.org/dc/terms/type",
    literal: false,
  },
  {
    q: "contactPoint",
    required: false,
    d: "An entity to contact",
    v: false,
    p: "http://www.w3.org/ns/dcat#contactPoint",
    literal: false,
  },
  {
    q: "spatial",
    required: false,
    d: "Spatial area or designed place",
    v: false,
    p: "http://www.w3.org/ns/dcat#spatial",
    literal: false,
  },
  {
    q: "temporal",
    required: false,
    d: "Time interval",
    v: false,
    p: "http://purl.org/dc/terms/temporal",
    literal: false,
  },
  {
    q: "issued",
    required: false,
    d: "The date the dataset was created",
    v: false,
    p: "http://purl.org/dc/terms/issued",
    literal: true,
  },
  {
    q: "modified",
    required: false,
    d: "The date the dataset was updated",
    v: false,
    p: "http://purl.org/dc/terms/modified",
    literal: true,
  },
  {
    q: "language",
    required: false,
    d: "Language of the resource",
    v: false,
    p: "http://purl.org/dc/terms/language",
    literal: false,
  },
  {
    q: "landingPage",
    required: false,
    d: "Links to other resources",
    v: false,
    p: "http://www.w3.org/ns/dcat#landingPage",
    literal: true,
  },
  {
    q: "politicalGeocodingLevelURI",
    required: false,
    d: "Geopolitical coverage of the dataset",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/politicalGeocodingLevelURI",
    literal: true,
  },
  {
    q: "politicalGeocodingURI",
    required: false,
    d: "URI of the administrative area",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/politicalGeocodingURI",
    literal: true,
  },
  {
    q: "availability",
    required: false,
    d: "Planned availability of the dataset",
    v: false,
    p: "http://data.europa.eu/r5r/availability",
    literal: false,
  },
  {
    q: "contributorID",
    required: false,
    d: "The identifier of the contributor",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/contributorID",
    literal: false,
  },
  {
    q: "geocodingDescription",
    required: false,
    d: "Description of the geocoding",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/geocodingDescription",
    literal: true,
  },
  {
    q: "versionInfo",
    required: false,
    d: "Version number of the dataset",
    v: false,
    p: "http://www.w3.org/2002/07/owl#versionInfo",
    literal: true,
  },
  {
    q: "versionNotes",
    required: false,
    d: "Notes on the version of the dataset",
    v: false,
    p: "http://www.w3.org/ns/adms#versionNotes",
    literal: true,
  },
  {
    q: "legalBasis",
    required: false,
    d: "Legal basis for the dataset",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/legalBasis",
    literal: true,
  },
  {
    q: "relation",
    required: false,
    d: "Related resource",
    v: false,
    p: "http://purl.org/dc/terms/relation",
    literal: false,
  },
  {
    q: "page",
    required: false,
    d: "Page reference",
    v: false,
    p: "http://xmlns.com/foaf/0.1/page",
    literal: false,
  },
  {
    q: "conformsTo",
    required: false,
    d: "Standard the dataset conforms to",
    v: false,
    p: "http://purl.org/dc/terms/conformsTo",
    literal: false,
  },
  {
    q: "accessRights",
    required: false,
    d: "Who can access the dataset",
    v: false,
    p: "http://purl.org/dc/terms/accessRights",
    literal: false,
  },
  {
    q: "provenance",
    required: false,
    d: "Development history of the dataset",
    v: false,
    p: "http://purl.org/dc/terms/provenance",
    literal: false,
  },
  {
    q: "accrualPeriodicity",
    required: false,
    d: "Frequency of dataset updates",
    v: false,
    p: "http://purl.org/dc/terms/accrualPeriodicity",
    literal: false,
  },
  {
    q: "qualityProcessURI",
    required: false,
    d: "URI of the quality process",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/qualityProcessURI",
    literal: true,
  },
  {
    q: "wasGeneratedBy",
    required: false,
    d: "Process that generated the dataset",
    v: false,
    p: "http://www.w3.org/ns/prov#wasGeneratedBy",
    literal: false,
  },
  {
    q: "spatialResolutionInMeters",
    required: false,
    d: "Spatial resolution of the dataset",
    v: false,
    p: "http://www.w3.org/ns/dcat#spatialResolutionInMeters",
    literal: true,
  },
  {
    q: "temporalResolution",
    required: false,
    d: "Temporal resolution of the dataset",
    v: false,
    p: "http://www.w3.org/ns/dcat#temporalResolution",
    literal: true,
  },
  {
    q: "granularity",
    required: false,
    d: "Granularity of the dataset",
    v: false,
    p: "http://www.w3.org/ns/dcat#granularity",
    literal: false,
  },
  {
    q: "qualifiedAttribution",
    required: false,
    d: "Attribution of the dataset",
    v: false,
    p: "http://www.w3.org/ns/prov#qualifiedAttribution",
    literal: false,
  },
  {
    q: "qualifiedRelation",
    required: false,
    d: "Relation of the dataset",
    v: false,
    p: "http://www.w3.org/ns/dcat#qualifiedRelation",
    literal: false,
  },
  {
    q: "isReferencedBy",
    required: false,
    d: "What references the dataset",
    v: false,
    p: "http://purl.org/dc/terms/isReferencedBy",
    literal: false,
  },
  {
    q: "references",
    required: false,
    d: "What is referenced by the dataset",
    v: false,
    p: "http://purl.org/dc/terms/references",
    literal: false,
  },
  {
    q: "source",
    required: false,
    d: "Source of the dataset",
    v: false,
    p: "http://purl.org/dc/terms/source",
    literal: false,
  },
  {
    q: "isVersionOf",
    required: false,
    d: "Resource derivated by the dataset",
    v: false,
    p: "http://purl.org/dc/terms/isVersionOf",
    literal: false,
  },
  {
    q: "sample",
    required: false,
    d: "Sample of the dataset",
    v: false,
    p: "http://www.w3.org/ns/adms#sample",
    literal: false,
  },
  {
    q: "creator",
    required: false,
    d: "Creator of the dataset",
    v: false,
    p: "http://purl.org/dc/terms/creator",
    literal: false,
  },
  {
    q: "contributor",
    required: false,
    d: "Contributor to the dataset",
    v: false,
    p: "http://purl.org/dc/terms/contributor",
    literal: false,
  },
  {
    q: "originator",
    required: false,
    d: "People who own the copyright",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/originator",
    literal: false,
  },
  {
    q: "maintainer",
    required: false,
    d: "People who maintain the dataset",
    v: false,
    p: "http://dcat-ap.de/def/dcatde/maintainer",
    literal: false,
  },
];

export const sparqlQueries = {
  options: [
    { label: "Default", value: "default" },
    { label: "Schule (Q3914)", value: "schools" },
    { label: "20 biggest cities in Germany", value: "twentyBiggestCities" },
    {
      label: "10 biggest football stadiums in Germany",
      value: "tenBiggestStadiums",
    },
    { label: "Krankenhaus (Q16917)", value: "hospitals" },
    { label: "Polizeistation (Q861951)", value: "policeStations" },
    { label: "Feuerwache (Q1195942)", value: "fireStations" },
    { label: "Supermarkt (Q180846)", value: "supermarkets" },
    { label: "Museen (Q33506)", value: "museums" },
    { label: "Bibliotheken (Q7075)", value: "libraries" },
    { label: "Bahnhöfe (Q55488)", value: "trainStations" },
    { label: "Banken (Q22687)", value: "banks" },
    { label: "Restaurants (Q11707)", value: "restaurants" },
    { label: "Kinos (Q41253)", value: "cinemas" },
    { label: "Denkmäler (Q4989906)", value: "monuments" },
    { label: "Hotels (Q27686)", value: "hotels" },
    { label: "Flughäfen (Q1248784)", value: "airports" },
    { label: "Stadien (Q483110)", value: "stadiums" },
    { label: "Schwimmbäder (Q200023)", value: "swimmingPools" },
    { label: "Tankstellen (Q205495)", value: "serviceStation" },
    { label: "Wetterstationen (Q190107)", value: "weatherStation" },
    {
      label: "Forschungslaboratorien (Q483242)",
      value: "researchLaboratory",
    },
    { label: "Häfen (Q44782)", value: "port" },
    { label: "Städte (Q515)", value: "cities" },
  ],
  queries: {
    default:
      "SELECT\n  ?s ?o\nWHERE {\n  ?s <http://www.opengis.net/ont/geosparql#asWKT> ?o .\n}\nLIMIT ",
    schools:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q3914> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    twentyBiggestCities:
      'SELECT DISTINCT ?city ?cityLabel ?latitude ?longitude ?instanceOfCity ?population WHERE {\n SERVICE wikibase:label { bd:serviceParam wikibase:language "de". } \n VALUES ?instanceOfCity { \n wd:Q515 \n  } \n  ?city (wdt:P31/(wdt:P279*)) ?instanceOfCity; \n wdt:P17 wd:Q183;\n  p:P625 ?statement. \n ?statement psv:P625 ?coordinate_node. \n ?coordinate_node wikibase:geoLatitude ?latitude; \n wikibase:geoLongitude ?longitude.\nOPTIONAL { ?city wdt:P1082 ?population. } \n } \nORDER BY DESC (?population) \nLIMIT 20',
    hospitals:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q16917> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    policeStations:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q861951> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    fireStations:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q1195942> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    supermarkets:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q180846> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    museums:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q33506> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    libraries:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q7075> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    trainStations:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q55488> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    banks:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q22687> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    restaurants:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q11707> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    cinemas:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q41253> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    monuments:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q4989906> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    hotels:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q27686> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    airports:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q1248784> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    stadiums:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q483110> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    swimmingPools:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q200023> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    serviceStation:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q205495> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    weatherStation:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q190107> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    researchLaboratory:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q483242> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    port: "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q44782> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
    cities:
      "SELECT ?item ?itemLabel ?coordinates ?category WHERE {\n ?item <spalod:category> <http://www.wikidata.org/entity/Q515> .\n  ?item <spalod:itemLabel> ?itemLabel .\n  ?item <spalod:coordinates> ?coordinates .\n ?item <spalod:category> ?category .} LIMIT ",
  },
};
